
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chengwei
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIFrame
     */
    private Passenger passenger= new Passenger(); 
    private Day date= new Day();
    private Flight flight= new Flight(); 
    private Waitlist Waitlist = new Waitlist(); 
    
    public GUIFrame() {
        initComponents();
        
        BookPassenger.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getPassenger().toArray()));
        BookDate.setModel(new javax.swing.DefaultComboBoxModel(date.getDate().toArray()));
        BookFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusDate.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        StatusPassenger.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getPassenger().toArray()));
        CancelPassenger.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getPassenger().toArray()));
        CancelDate.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        DropFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AddPassengerText = new javax.swing.JTextField();
        AddPassengerButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BookPassenger = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        BookFlight = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        BookDate = new javax.swing.JComboBox<>();
        AddBookingButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        StatusPassenger = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        StatusFlight = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        StatusDate = new javax.swing.JComboBox<>();
        BookedStatusButton = new javax.swing.JButton();
        WaitlistStatusButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookingWaitlistTable = new javax.swing.JTable();
        PassengerStatusButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CancelDate = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        CancelPassenger = new javax.swing.JComboBox<>();
        CancelPassengerButton = new javax.swing.JButton();
        CancelBookingJlabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AddDaySpinner = new javax.swing.JSpinner();
        AddDayButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        FlightNameText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        seatsSpinner = new javax.swing.JSpinner();
        AddFlightButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        DropFlight = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 36)); // NOI18N
        jLabel1.setText("    Flight Scheduler");

        jLabel2.setText("Passenger Name: ");

        AddPassengerButton.setText("Add");
        AddPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddPassengerText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(AddPassengerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AddPassengerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddPassengerButton)
                .addGap(0, 157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Passenger", jPanel1);

        jLabel3.setText("Passenger Name: ");

        BookPassenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BookPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPassengerActionPerformed(evt);
            }
        });

        jLabel4.setText("Flight:");

        BookFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Date: ");

        BookDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddBookingButton.setText("Book");
        AddBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(AddBookingButton)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BookPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BookFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddBookingButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        jLabel6.setText("Passenger Name: ");

        StatusPassenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Flight: ");

        StatusFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Date: ");

        StatusDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BookedStatusButton.setText("Booked State");
        BookedStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookedStatusButtonActionPerformed(evt);
            }
        });

        WaitlistStatusButton.setText(" Waitlist State");
        WaitlistStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WaitlistStatusButtonActionPerformed(evt);
            }
        });

        BookingWaitlistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(BookingWaitlistTable);

        PassengerStatusButton.setText("Passenger State");
        PassengerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassengerStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(StatusPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WaitlistStatusButton)
                            .addComponent(BookedStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassengerStatusButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 222, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(StatusPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassengerStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(StatusFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(StatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BookedStatusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WaitlistStatusButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        jTabbedPane1.addTab("Status", jPanel3);

        jLabel9.setText("Flight Date: ");

        CancelDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CancelDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelDateActionPerformed(evt);
            }
        });

        jLabel10.setText("Passenger: ");

        CancelPassenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CancelPassengerButton.setText("Cancel Passenger");
        CancelPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelPassengerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CancelPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(CancelPassengerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(CancelBookingJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CancelPassenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelPassengerButton)
                    .addComponent(CancelBookingJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel Passenger", jPanel4);

        jLabel11.setText("Date: ");

        AddDaySpinner.setModel(new javax.swing.SpinnerDateModel());

        AddDayButton.setText("Add");
        AddDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(AddDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Date", jPanel5);

        jLabel12.setText("Flight:");

        jLabel13.setText("Number of Seats: ");

        AddFlightButton.setText("Add");
        AddFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddFlightButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlightNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(FlightNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(seatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddFlightButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Flight", jPanel6);

        jLabel14.setText("Flight: ");

        DropFlight.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Drop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel14)
                        .addGap(34, 34, 34)
                        .addComponent(DropFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1)))
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(DropFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Flight", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengerButtonActionPerformed
        // TODO add your handling code here:
        int result = passenger.addPassenger(AddPassengerText.getText());
        
        if(result == 1)
            JOptionPane.showMessageDialog(this, "Passenger added","Passenger added", JOptionPane.PLAIN_MESSAGE);
        else
             JOptionPane.showMessageDialog(this, "Passenger not Added!","Error", JOptionPane.PLAIN_MESSAGE); 
        
        BookPassenger.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getPassenger().toArray()));
        StatusPassenger.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getPassenger().toArray()));
        CancelPassenger.setModel(new javax.swing.DefaultComboBoxModel(Passenger.getPassenger().toArray()));
    }//GEN-LAST:event_AddPassengerButtonActionPerformed

    private void BookedStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookedStatusButtonActionPerformed
        // TODO add your handling code here:
        Date parsed = Date.valueOf(StatusDate.getSelectedItem().toString());
        BookingWaitlistTable.setModel(Booking.settingJTable(parsed, StatusFlight.getSelectedItem().toString()));
    }//GEN-LAST:event_BookedStatusButtonActionPerformed

    private void WaitlistStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WaitlistStatusButtonActionPerformed
        // TODO add your handling code here:
        Date parsed = Date.valueOf(StatusDate.getSelectedItem().toString());
        BookingWaitlistTable.setModel(Waitlist.settingJTable(parsed));
    }//GEN-LAST:event_WaitlistStatusButtonActionPerformed

    private void AddBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookingButtonActionPerformed
        // TODO add your handling code here:
        String flightType = (String) BookFlight.getSelectedItem();
        String passengerName =  (String) BookPassenger.getSelectedItem();
        Date flightDate=null;
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date date = sdf1.parse((String) BookDate.getSelectedItem());
            flightDate = new java.sql.Date(date.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        int total_seats = Flight.getSeats(flightType);
        int booked_seats = Booking.getBookCount(flightType, flightDate);
        
        java.sql.Timestamp passengerPosition = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        if (total_seats > booked_seats)
        {
            Booking.addBooking(passengerName, flightDate, flightType);
            JOptionPane.showMessageDialog(this, "Booking succeed!","Success", JOptionPane.PLAIN_MESSAGE); 
            
        }
        else
        {
            Waitlist.addWaitlist(passengerName, flightDate, flightType, passengerPosition);
            JOptionPane.showMessageDialog(this, "Passenger added to waitlist!","Error", JOptionPane.PLAIN_MESSAGE); 
        }
    }//GEN-LAST:event_AddBookingButtonActionPerformed

    private void AddDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDayButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd"); 
        String spinnerValue = formater.format(AddDaySpinner.getValue()); 
        Date date = Date.valueOf(spinnerValue);
        int result = Day.addDate(date);
        
        if(result == 1)
            JOptionPane.showMessageDialog(this, "Date added","Passenger added", JOptionPane.PLAIN_MESSAGE);
        else
             JOptionPane.showMessageDialog(this, "Date not Added","Error", JOptionPane.PLAIN_MESSAGE);
        
        StatusDate.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        CancelDate.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
        BookDate.setModel(new javax.swing.DefaultComboBoxModel(Day.getDate().toArray()));
    }//GEN-LAST:event_AddDayButtonActionPerformed

    private void AddFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightButtonActionPerformed
        // TODO add your handling code here:
        int result = Flight.addFlight(FlightNameText.getText(),(int) seatsSpinner.getValue());
        
        if(result == 1)
            JOptionPane.showMessageDialog(this, "Flight added","Passenger added", JOptionPane.PLAIN_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Flight not added","Error", JOptionPane.PLAIN_MESSAGE); 
        
        BookFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
    }//GEN-LAST:event_AddFlightButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String drop_flight = DropFlight.getItemAt (DropFlight.getSelectedIndex());;
        Flight.deleteFlight(drop_flight);
        
        if (drop_flight != null)
            JOptionPane.showMessageDialog(this, "Flight dropped","Succcess", JOptionPane.PLAIN_MESSAGE); 
        else
            JOptionPane.showMessageDialog(this, "Flight not dropped","Error", JOptionPane.PLAIN_MESSAGE); 
        
        Flight.deleteBook(drop_flight);
        Flight.deleteWaitList(drop_flight);
        Flight.getPassengersBook(drop_flight);
        Flight.getPassengersDate(drop_flight);
        //Flight.getPassengersWaitList(drop_flight);
        
        BookFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        StatusFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
        DropFlight.setModel(new javax.swing.DefaultComboBoxModel(flight.getFlight().toArray()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BookPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPassengerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookPassengerActionPerformed

    private void PassengerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassengerStatusButtonActionPerformed
        // TODO add your handling code here:
                
        try {
            BookingWaitlistTable.setModel (Passenger.settingJTable((String) StatusPassenger.getSelectedItem()));
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_PassengerStatusButtonActionPerformed

    private void CancelDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelDateActionPerformed

    private void CancelPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelPassengerButtonActionPerformed
        // TODO add your handling code here:
        String cancel_Passenger = CancelPassenger.getItemAt (CancelPassenger.getSelectedIndex());
        Date cancel_Date = Date.valueOf(CancelDate.getSelectedItem().toString());
        int number = 0;
        String status = "";
        String currentFlight;
        currentFlight = Booking.getPassengerBooking(cancel_Passenger, cancel_Date);
        if (currentFlight != null)
        {
            System.out.println("Passenger was found in bookings, removing now");
            System.out.println("Current flight is " + currentFlight);
            Booking.cancelBooking(cancel_Passenger, cancel_Date);
            status += "Passenger " + cancel_Passenger + " Cancelled.";
            
            String book_passenger = Waitlist.waitlistPassengerDate(currentFlight, cancel_Date);
            if (book_passenger != null)
            {
                java.sql.Timestamp newTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
                Booking.bookFlight(cancel_Date,currentFlight, book_passenger, newTimestamp);
                status +=  book_passenger + " was added";
                Waitlist.cancelWaitlist(book_passenger, cancel_Date);
            }
            
            
            CancelBookingJlabel.setText(status);
       
        }
        else
        {
            System.out.println("Passenger was not found in bookings, Checking Waitlist");
            number = Waitlist.cancelWaitlist(cancel_Passenger, cancel_Date);
            
            if (number == 0)
            {
                CancelBookingJlabel.setText("Passenger is not booked instead waitlisted for this date");
            }
            else
            {
                CancelBookingJlabel.setText("Passenger removed from waitlist for this date");
            }
        }
    }//GEN-LAST:event_CancelPassengerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookingButton;
    private javax.swing.JButton AddDayButton;
    private javax.swing.JSpinner AddDaySpinner;
    private javax.swing.JButton AddFlightButton;
    private javax.swing.JButton AddPassengerButton;
    private javax.swing.JTextField AddPassengerText;
    private javax.swing.JComboBox<String> BookDate;
    private javax.swing.JComboBox<String> BookFlight;
    private javax.swing.JComboBox<String> BookPassenger;
    private javax.swing.JButton BookedStatusButton;
    private javax.swing.JTable BookingWaitlistTable;
    private javax.swing.JLabel CancelBookingJlabel;
    private javax.swing.JComboBox<String> CancelDate;
    private javax.swing.JComboBox<String> CancelPassenger;
    private javax.swing.JButton CancelPassengerButton;
    private javax.swing.JComboBox<String> DropFlight;
    private javax.swing.JTextField FlightNameText;
    private javax.swing.JButton PassengerStatusButton;
    private javax.swing.JComboBox<String> StatusDate;
    private javax.swing.JComboBox<String> StatusFlight;
    private javax.swing.JComboBox<String> StatusPassenger;
    private javax.swing.JButton WaitlistStatusButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner seatsSpinner;
    // End of variables declaration//GEN-END:variables
}
